export const macedonian_cities = [
  "Skopje",
  "Tetovo",
  "Bitola",
  "Kumanovo",
  "Prilep",
  "Ohrid",
  "Strumica",
  "Veles",
  "Štip",
  "Kavadarci",
  "Gostivar",
  "Kočani",
  "Kičevo",
  "Struga",
  "Radoviš",
  "Gevgelija",
  "Debar",
  "Kriva Palanka",
  "Sveti Nikole",
  "Negotino",
  "Delčevo",
  "Vinica",
  "Probištip",
  "Aračinovo",
  "Berovo",
  "Kratovo",
  "Bogovinje",
  "Bogdanci",
  "Studeničani",
  "Sopište",
  "Kruševo",
  "Vrapčište",
  "Valandovo",
  "Želino",
  "Tearce",
  "Makedonski Brod",
  "Demir Kapija",
  "Pehčevo",
  "Brvenica",
  "Novo Selo",
  "Vevčani",
  "Petrovec",
  "Lipkovo",
  "Demir Hisar",
  "Rosoman",
  "Plasnica",
  "Mogila",
  "Krivogaštani",
  "Zrnovci",
  "Gradsko",
  "Vasilevo",
  "Bosilovo",
  "Staro Nagoričane",
  "Rankovce",
  "Novaci",
  "Konče",
  "Obleševo",
  "Belčišta",
  "Jegunovce",
  "Lozovo",
  "Dolneni",
  "Rostuša",
  "Centar Župa",
  "Zelenikovo",
  "Čučer-Sandevo",
  "Karbinci",
  "Star Dojran",
  "Ilinden",
  "Makedonska Kamenica",
  "Resen",
];
